# -*- coding: utf-8 -*-
"""image_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Es23_70PvV6ZZw6GcRU1ctuUlfhLhSwG
"""

# 각종 모듈 import
import io
import json

import torchvision.transforms as transforms
from PIL import Image
from flask import Flask, jsonify, request

import GoogLeNet

app = Flask(__name__)

imagenet_class_index = json.load(open('D:/2020GP/2020gp/2020ML_P/pyflask/static/imagenet_class_index.json'))

# 학습 모델 불러오기
model = GoogLeNet.GoogLeNet(4)
path = "D:/2020GP/2020gp/2020ML_P/pyflask/model/"
load_model.load_state_dict(torch.load(path+"model_state_dict_epoch10_2.pt", map_location='cpu'),strict=False)
load_model.eval()

# 입력 이미지 전처리 함수 (image_bytes 매개변수 수정 필요해보임)
def transform_image(image_bytes):
    my_transforms = transforms.Compose([transforms.Resize(224),
                                        transforms.CenterCrop(224),
                                        transforms.ToTensor(),
                                        transforms.Normalize(
                                            [0.485, 0.456, 0.406],
                                            [0.229, 0.224, 0.225])])
    image = Image.open(io.BytesIO(image_bytes))
    return my_transforms(image).unsqueeze(0)
    # image.save('./pyflask/static/images/'+str(user_img.filename))

# 이미지 입력 받고 사진 저장
@app.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        user_img = request.files['user_img']
		user_img.save('./pyflask/static/images/'+str(user_img.filename))
		user_img_path = './static/images/'+str(user_img.filename)

        # user_img.save('./pyflask/static/images/'+str(user_img.filename))  이미지를 세이브를 할까 말까 고민중
        #img_bytes = user_img.read()

		img = Image.open(user_img_path).convert("L")
        class_id, class_name = get_prediction(image_bytes=img_bytes)
        return jsonify({'class_id': class_id, 'class_name': class_name})

if __name__ == '__main__':
    app.run()